FROM odoo:18.0

# Copy custom addons into Odoo extra-addons path
COPY addons /mnt/extra-addons

# (Optional) Install Python dependencies for addons
# COPY requirements.txt /tmp/requirements.txt
# RUN pip install --no-cache-dir -r /tmp/requirements.txt
