name: Build & Deploy Odoo Sandbox

on:
  push:
    branches: [main]

env:
  IMAGE: ghcr.io/minhmaxsolution/odoo-community-sandbox:latest

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: ${{ env.IMAGE }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}
      - name: Pull & restart via compose on server
        run: |
          ssh -o StrictHostKeyChecking=no deploy@${{ secrets.DEPLOY_HOST }} '
            set -e
            cd /opt/odoo-stack/app
            docker compose pull
            docker compose up -d
            docker image prune -f
          '
